### ISSUE TITLE
IE 11 linie verschoben

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/amorelie#2]
![image](https://cloud.githubusercontent.com/assets/19430535/19721716/d06fd020-9b73-11e6-8143-ec26b3f00f59.png)

taucht nur nur im IE 11 auf

**Comment by kremin** [comment]
https://app.crossbrowsertesting.com/public/ibf724ec68acbad9/livetests/6238791/snapshots/z79d3e1d38a66afc1c23
