### ISSUE TITLE
"teilen" buttons verschwunden

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/amorelie#3]
so sieht das bei marie auf dem chrome 53 / mac os X aus:

![bildschirmfoto 2016-10-26 um 14 48 52](https://cloud.githubusercontent.com/assets/19430535/19759742/a1129c7a-9c2e-11e6-9285-b563acd7c2d1.png)

**Comment by kremin** [comment]
schau ich mir an.

**Comment by kremin** [comment]
https://app.crossbrowsertesting.com/public/ibf724ec68acbad9/screenshots/zb48ec98aa940889bd10
